import { html, css, LitElement } from '../assets/lit-core-2.7.4.min.js';

/**
 * DocumentPreview - Displays generated professional documents in conversation
 *
 * Shows documents generated by AI workflows with preview and export options.
 * Supports PDF, DOCX, and Markdown export formats.
 */
export class DocumentPreview extends LitElement {
    static properties = {
        document: { type: Object },
        expanded: { type: Boolean, state: true },
        exporting: { type: String, state: true }  // 'pdf', 'docx', 'md', or null
    };

    static styles = css`
        * {
            font-family: var(--font-family-primary);
            cursor: default;
            user-select: text;
        }

        :host {
            display: block;
            width: 100%;
            margin: 12px 0;
        }

        .document-container {
            background: var(--color-white-05);
            border: 1px solid var(--color-white-15);
            border-radius: 12px;
            overflow: hidden;
            transition: all 0.2s ease;
        }

        .document-container:hover {
            border-color: var(--color-white-25);
        }

        .document-header {
            display: flex;
            align-items: center;
            justify-content: space-between;
            padding: 12px 16px;
            background: var(--color-white-08);
            border-bottom: 1px solid var(--color-white-15);
            cursor: pointer;
            transition: background 0.15s ease;
        }

        .document-header:hover {
            background: var(--color-white-12);
        }

        .document-title-section {
            display: flex;
            align-items: center;
            gap: 10px;
            flex: 1;
        }

        .document-icon {
            font-size: 24px;
            flex-shrink: 0;
        }

        .document-info {
            flex: 1;
            min-width: 0;
        }

        .document-title {
            font-size: 13px;
            font-weight: 600;
            color: var(--color-white-90);
            margin-bottom: 2px;
        }

        .document-meta {
            font-size: 11px;
            color: var(--color-white-60);
            display: flex;
            align-items: center;
            gap: 8px;
        }

        .document-type-badge {
            background: rgba(255, 255, 255, 0.1);
            padding: 2px 6px;
            border-radius: 4px;
            font-size: 10px;
            font-weight: 500;
            color: var(--color-white-70);
        }

        .document-actions {
            display: flex;
            align-items: center;
            gap: 6px;
        }

        .toggle-btn {
            background: transparent;
            border: none;
            color: var(--color-white-60);
            font-size: 14px;
            cursor: pointer;
            padding: 4px 8px;
            border-radius: 4px;
            transition: all 0.15s ease;
        }

        .toggle-btn:hover {
            background: rgba(255, 255, 255, 0.1);
            color: var(--color-white-90);
        }

        .toggle-btn.expanded {
            transform: rotate(180deg);
        }

        .export-btn {
            background: rgba(255, 255, 255, 0.08);
            border: 1px solid rgba(255, 255, 255, 0.2);
            color: var(--color-white-80);
            font-size: 11px;
            font-weight: 500;
            cursor: pointer;
            padding: 6px 12px;
            border-radius: 6px;
            transition: all 0.15s ease;
            display: flex;
            align-items: center;
            gap: 6px;
        }

        .export-btn:hover {
            background: rgba(255, 255, 255, 0.15);
            border-color: rgba(255, 255, 255, 0.3);
            color: var(--color-white-95);
        }

        .export-btn:active {
            transform: scale(0.95);
        }

        .export-btn.exporting {
            opacity: 0.6;
            cursor: wait;
        }

        .document-content {
            padding: 16px;
            max-height: 500px;
            overflow-y: auto;
        }

        .document-content.collapsed {
            display: none;
        }

        .document-body {
            font-size: 12px;
            line-height: 1.6;
            color: var(--color-white-85);
            white-space: pre-wrap;
            word-wrap: break-word;
        }

        /* Markdown-style formatting */
        .document-body h1,
        .document-body h2,
        .document-body h3,
        .document-body h4,
        .document-body h5,
        .document-body h6 {
            color: var(--color-white-95);
            margin: 16px 0 8px 0;
            font-weight: 600;
        }

        .document-body h1 { font-size: 18px; }
        .document-body h2 { font-size: 16px; }
        .document-body h3 { font-size: 14px; }
        .document-body h4 { font-size: 13px; }

        .document-body p {
            margin: 8px 0;
        }

        .document-body ul,
        .document-body ol {
            margin: 8px 0;
            padding-left: 24px;
        }

        .document-body li {
            margin: 4px 0;
        }

        .document-body strong {
            font-weight: 600;
            color: var(--color-white-90);
        }

        .document-body em {
            font-style: italic;
            color: var(--color-white-80);
        }

        .document-body code {
            background: var(--color-black-20);
            padding: 2px 6px;
            border-radius: 3px;
            font-family: var(--font-family-mono);
            font-size: 11px;
            color: rgba(255, 200, 0, 0.9);
        }

        .document-body pre {
            background: var(--color-black-20);
            padding: 12px;
            border-radius: 6px;
            overflow-x: auto;
            margin: 12px 0;
        }

        .document-body pre code {
            background: none;
            padding: 0;
        }

        .document-footer {
            padding: 12px 16px;
            background: var(--color-white-05);
            border-top: 1px solid var(--color-white-10);
            display: flex;
            align-items: center;
            justify-content: space-between;
            gap: 8px;
        }

        .export-options {
            display: flex;
            gap: 6px;
            flex-wrap: wrap;
        }

        .export-option {
            background: rgba(255, 255, 255, 0.05);
            border: 1px solid rgba(255, 255, 255, 0.15);
            color: var(--color-white-75);
            font-size: 11px;
            font-weight: 500;
            cursor: pointer;
            padding: 6px 10px;
            border-radius: 6px;
            transition: all 0.15s ease;
            display: flex;
            align-items: center;
            gap: 5px;
        }

        .export-option:hover {
            background: rgba(255, 255, 255, 0.1);
            border-color: rgba(255, 255, 255, 0.25);
            color: var(--color-white-90);
        }

        .export-option.exporting {
            opacity: 0.6;
            cursor: wait;
        }

        .spinner {
            display: inline-block;
            width: 10px;
            height: 10px;
            border: 2px solid rgba(255, 255, 255, 0.3);
            border-top-color: rgba(255, 255, 255, 0.9);
            border-radius: 50%;
            animation: spin 0.6s linear infinite;
        }

        @keyframes spin {
            to { transform: rotate(360deg); }
        }

        /* Scrollbar styling */
        .document-content::-webkit-scrollbar {
            width: 8px;
        }

        .document-content::-webkit-scrollbar-track {
            background: var(--color-black-20);
            border-radius: 4px;
        }

        .document-content::-webkit-scrollbar-thumb {
            background: var(--color-white-20);
            border-radius: 4px;
        }

        .document-content::-webkit-scrollbar-thumb:hover {
            background: var(--color-white-30);
        }
    `;

    constructor() {
        super();
        this.document = null;
        this.expanded = false;
        this.exporting = null;
    }

    getDocumentIcon(type) {
        const iconMap = {
            'cv': '📄',
            'lettre': '✉️',
            'rapport': '📊',
            'presentation': '📽️',
            'article': '📰',
            'memo': '📝',
            'contrat': '📜',
            'default': '📑'
        };
        return iconMap[type?.toLowerCase()] || iconMap.default;
    }

    toggleExpanded() {
        this.expanded = !this.expanded;
    }

    async handleExport(format) {
        if (this.exporting || !this.document) return;

        this.exporting = format;
        this.requestUpdate();

        try {
            console.log(`[DocumentPreview] Exporting document to ${format.toUpperCase()}...`);

            // Call export service
            const result = await window.api.documents.exportDocument({
                title: this.document.title,
                content: this.document.content,
                type: this.document.type,
                format: format
            });

            if (result.success) {
                console.log(`[DocumentPreview] Export successful: ${result.filePath}`);

                // Show notification or alert
                this.dispatchEvent(new CustomEvent('export-success', {
                    detail: { format, filePath: result.filePath },
                    bubbles: true,
                    composed: true
                }));
            } else {
                throw new Error(result.error || 'Export failed');
            }
        } catch (error) {
            console.error('[DocumentPreview] Export error:', error);

            this.dispatchEvent(new CustomEvent('export-error', {
                detail: { format, error: error.message },
                bubbles: true,
                composed: true
            }));
        } finally {
            this.exporting = null;
            this.requestUpdate();
        }
    }

    formatContent(content) {
        if (!content) return '';

        // Basic markdown-style formatting
        // This is a simple implementation - for full markdown, use marked.js
        let formatted = content;

        // Headers
        formatted = formatted.replace(/^### (.*$)/gim, '<h3>$1</h3>');
        formatted = formatted.replace(/^## (.*$)/gim, '<h2>$1</h2>');
        formatted = formatted.replace(/^# (.*$)/gim, '<h1>$1</h1>');

        // Bold and italic
        formatted = formatted.replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>');
        formatted = formatted.replace(/\*([^*]+)\*/g, '<em>$1</em>');

        // Code
        formatted = formatted.replace(/`([^`]+)`/g, '<code>$1</code>');

        return formatted;
    }

    render() {
        if (!this.document) {
            return html``;
        }

        const { title, content, type, metadata } = this.document;
        const wordCount = content?.split(/\s+/).length || 0;
        const charCount = content?.length || 0;

        return html`
            <div class="document-container">
                <div class="document-header" @click=${this.toggleExpanded}>
                    <div class="document-title-section">
                        <div class="document-icon">
                            ${this.getDocumentIcon(type)}
                        </div>
                        <div class="document-info">
                            <div class="document-title">${title || 'Document sans titre'}</div>
                            <div class="document-meta">
                                <span class="document-type-badge">${type?.toUpperCase() || 'DOCUMENT'}</span>
                                <span>${wordCount} mots</span>
                                <span>${charCount} caractères</span>
                            </div>
                        </div>
                    </div>
                    <div class="document-actions">
                        <button class="toggle-btn ${this.expanded ? 'expanded' : ''}" title="Afficher/Masquer">
                            ▼
                        </button>
                    </div>
                </div>

                <div class="document-content ${this.expanded ? '' : 'collapsed'}">
                    <div class="document-body" .innerHTML=${this.formatContent(content)}></div>
                </div>

                <div class="document-footer">
                    <div style="font-size: 10px; color: var(--color-white-50);">
                        Exporter en :
                    </div>
                    <div class="export-options">
                        <button
                            class="export-option ${this.exporting === 'pdf' ? 'exporting' : ''}"
                            @click=${() => this.handleExport('pdf')}
                            ?disabled=${this.exporting}
                            title="Exporter en PDF"
                        >
                            ${this.exporting === 'pdf' ? html`<span class="spinner"></span>` : '📄'} PDF
                        </button>
                        <button
                            class="export-option ${this.exporting === 'docx' ? 'exporting' : ''}"
                            @click=${() => this.handleExport('docx')}
                            ?disabled=${this.exporting}
                            title="Exporter en Word"
                        >
                            ${this.exporting === 'docx' ? html`<span class="spinner"></span>` : '📝'} DOCX
                        </button>
                        <button
                            class="export-option ${this.exporting === 'md' ? 'exporting' : ''}"
                            @click=${() => this.handleExport('md')}
                            ?disabled=${this.exporting}
                            title="Exporter en Markdown"
                        >
                            ${this.exporting === 'md' ? html`<span class="spinner"></span>` : '📋'} MD
                        </button>
                    </div>
                </div>
            </div>
        `;
    }
}

customElements.define('document-preview', DocumentPreview);
